### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by ManiDeepakReddyAila** [BigDataIA-Spring2023-Team-05/Assignment-03#32]
I was able to register but was not able to login, so couldn't test it.

`Traceback (most recent call last):
File "/Users/manideepakreddyaila/Desktop/test/Assignment-03/CLI-v2/main.py", line 210, in <module>
app()
File "/Users/manideepakreddyaila/Desktop/test/Assignment-03/CLI-v2/main.py", line 48, in login
delete token()
File "/Users/manideepakreddyaila/Desktop/test/Assignment-03/CLI-v2/main.py", line 204, in delete_token
f
= open("./data/config",
FileNotFoundError: [Errno 2] No such file or directory:
'./data/config'`

**Comment by ManiDeepakReddyAila** [comment]
<img width="987" alt="Screen Shot 2023-03-17 at 12 58 31 PM" src="https://user-images.githubusercontent.com/114799981/225973549-d06f39b1-2bf0-44f1-ad15-09391cc9bded.png">

**Comment by HeyIts-RJ** [comment]
Did you deleted any directories while running the CLI? Can you share the screenshot of the directory in which you are running CLI commands?

**Comment by Charan-Patnaik** [comment]
Also the above mentioned point on unable to login should not exist since we have demonstrated successfully in the presentation , please have a look.

**Comment by HeyIts-RJ** [comment]
<img width="1114" alt="Screenshot 2023-03-17 at 3 48 59 PM" src="https://user-images.githubusercontent.com/39235247/226014319-8f20faed-7355-4a72-8adc-32f6da61aefd.png">

I cloned the repo and I am able to sign up and log in to my user account. You might have made some changes in the directory.

**Comment by ManiDeepakReddyAila** [comment]
Steps followed:

- git clone https://github.com/BigDataIA-Spring2023-Team-05/Assignment-03.git
- cd Assignment-03
- python -m vent vent_test
- source vent_test/bin/activate
- pip install -r backend/requirements.txt
- python CLI-v2/main.py create-user
- python CLI-v2/main.py login

This gives me error saying ./data/config file or directory doesn't exist

Please let me know if I'm doing it wrong at any step.

**Comment by HeyIts-RJ** [comment]
> Steps followed:
> 
> * git clone https://github.com/BigDataIA-Spring2023-Team-05/Assignment-03.git
> * cd Assignment-03
> * python -m vent vent_test
> * source vent_test/bin/activate
> * pip install -r backend/requirements.txt
> * python CLI-v2/main.py create-user
> * python CLI-v2/main.py login
> 
> This gives me error saying ./data/config file or directory doesn't exist
> 
> Please let me know if I'm doing it wrong at any step.

Please follow these steps before running any CLI command, Navigate into **CLI-v2** directory.

`cd CLI-v2`

then try executing `python main.py create-user` or `python main.py login`
